# Builds the little project logos shown on each plugin card.
#
# These identify which project a plugin came from, the way Equicord's own plugin list does.
# They are inlined as data URIs rather than fetched from each project's website, because a
# plugin list that makes four cross-site requests to render its badges is a worse trade
# than a few KB in the bundle - and it keeps working offline.
#
# Sources live in assets/sources/. Run with: pnpm makeSourceLogos

#Requires -Version 5.1
[CmdletBinding()]
param([int] $Size = 32)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$Root = Split-Path -Parent $PSScriptRoot
$SourceDir = Join-Path $Root "assets\sources"
$TsOut = Join-Path $Root "src\utils\pluginSourceLogos.ts"

$marks = @("vencord", "equicord", "endcord")
$encoded = @{}

foreach ($name in $marks) {
    $path = Join-Path $SourceDir "$name.png"
    if (-not (Test-Path $path)) { throw "Missing $path" }

    $src = [System.Drawing.Image]::FromFile($path)
    $bmp = New-Object System.Drawing.Bitmap $Size, $Size
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = "AntiAlias"
    $g.InterpolationMode = "HighQualityBicubic"
    $g.PixelOffsetMode = "HighQuality"
    $g.Clear([System.Drawing.Color]::Transparent)

    # Fit rather than fill: these logos are different aspect ratios and cropping any of
    # them would cut into the mark.
    $scale = [math]::Min($Size / $src.Width, $Size / $src.Height)
    $w = [int]($src.Width * $scale)
    $h = [int]($src.Height * $scale)
    $g.DrawImage($src, [int](($Size - $w) / 2), [int](($Size - $h) / 2), $w, $h)
    $g.Dispose()

    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $encoded[$name] = [Convert]::ToBase64String($ms.ToArray())
    $ms.Dispose(); $bmp.Dispose(); $src.Dispose()

    Write-Host "  $name -> $($encoded[$name].Length) chars"
}

$text = @"
/*
 * Xbtcord, a Discord client mod
 * Copyright (c) 2026 Xbtcord and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * Generated by scripts/makeSourceLogos.ps1 - do not edit by hand.
 *
 * Each project's own logo, used to mark which one a plugin came from. Inlined so the
 * plugin list does not make a cross-site request per badge just to render itself.
 *
 * These marks belong to their respective projects and are used here only to identify
 * where a plugin came from.
 */

export const VENCORD_LOGO = "data:image/png;base64,$($encoded['vencord'])";
export const EQUICORD_LOGO = "data:image/png;base64,$($encoded['equicord'])";
export const ENDCORD_LOGO = "data:image/png;base64,$($encoded['endcord'])";
"@

Set-Content -Path $TsOut -Value $text -Encoding utf8
Write-Host "wrote $TsOut ($([math]::Round((Get-Item $TsOut).Length / 1KB)) KB)"
