# Builds the icons for connections Discord does not know about.
#
# Discord renders a connection's icon from its own platform table, so anything it has never
# heard of comes out blank. Sites we add ourselves need their mark carried in the bundle
# instead - inlined as a data URI, so rendering a profile never fetches from a third party.
#
# Sources live in assets/. Run with: pnpm makeConnectionIcons

#Requires -Version 5.1
[CmdletBinding()]
param([int] $Size = 48)

$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$Root = Split-Path -Parent $PSScriptRoot
$TsOut = Join-Path $Root "src\utils\connectionIcons.ts"

# name in the generated file -> source png
$icons = @{ "ISNTRIP_ICON" = "isntrip.png" }
$encoded = @{}

foreach ($name in $icons.Keys) {
    $path = Join-Path $Root "assets\$($icons[$name])"
    if (-not (Test-Path $path)) { throw "Missing $path" }

    $src = [System.Drawing.Image]::FromFile($path)
    $bmp = New-Object System.Drawing.Bitmap $Size, $Size
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = "AntiAlias"
    $g.InterpolationMode = "HighQualityBicubic"
    $g.PixelOffsetMode = "HighQuality"
    $g.Clear([System.Drawing.Color]::Transparent)

    # Fit, not fill - these are square marks and cropping would clip the artwork.
    $scale = [math]::Min($Size / $src.Width, $Size / $src.Height)
    $w = [int]($src.Width * $scale)
    $h = [int]($src.Height * $scale)
    $g.DrawImage($src, [int](($Size - $w) / 2), [int](($Size - $h) / 2), $w, $h)
    $g.Dispose()

    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $encoded[$name] = [Convert]::ToBase64String($ms.ToArray())
    $ms.Dispose(); $bmp.Dispose(); $src.Dispose()

    Write-Host "  $name -> $($encoded[$name].Length) chars"
}

$text = @"
/*
 * Xbtcord, a Discord client mod
 * Copyright (c) 2026 Xbtcord and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * Generated by scripts/makeConnectionIcons.ps1 - do not edit by hand.
 *
 * Icons for connection types Discord has no platform entry for. Inlined rather than
 * hotlinked so that opening a profile never makes a request to a third party.
 *
 * These marks belong to their respective sites and are used only to label a link to them.
 */

export const ISNTRIP_ICON = "data:image/png;base64,$($encoded['ISNTRIP_ICON'])";
"@

# UTF-8 with no BOM. Set-Content -Encoding utf8 writes one on PowerShell 5.1, and the
# repo's header lint sees those three bytes sitting in front of the comment and rejects the
# file as having no licence header.
# The trailing newline matters too - WriteAllText adds none, and the lint wants one.
[System.IO.File]::WriteAllText($TsOut, $text + "`n", (New-Object System.Text.UTF8Encoding $false))
Write-Host "wrote $TsOut ($([math]::Round((Get-Item $TsOut).Length / 1KB)) KB)"
