# Builds the Xbtcord installer.
#
# Works with either toolchain, because the two situations this gets built in are different:
# CI has Visual Studio, and a contributor's machine is far more likely to have a portable
# MinGW than a 7 GB Visual Studio install.
#
#   .\build.ps1                          # auto-detect, no release source baked in
#   .\build.ps1 -Repo you/xbtcord        # point the built exe at a release source
#   .\build.ps1 -Toolchain mingw         # force one
#
# The output is installer\build\XbtcordInstaller.exe, self-contained apart from the DLLs
# that ship with Windows.

#Requires -Version 5.1
[CmdletBinding()]
param(
    [string] $Repo = "",
    [ValidateSet("auto", "msvc", "mingw")]
    [string] $Toolchain = "auto"
)

$ErrorActionPreference = "Stop"

$Here = $PSScriptRoot
$Out = Join-Path $Here "build"
$Exe = Join-Path $Out "XbtcordInstaller.exe"
$Source = Join-Path $Here "xbtcord-installer.cpp"
$Rc = Join-Path $Here "installer.rc"
$Config = Join-Path $Out "repo_config.h"

New-Item -ItemType Directory -Path $Out -Force | Out-Null

# The repository is handed to the compiler as a generated header rather than a -D flag.
# A define like -DXBT_REPO=L"owner/repo" loses its quotes somewhere between PowerShell, cmd
# and the compiler, and fails as "'Lowner' was not declared in this scope". A header has no
# quoting layers to survive.
if ($Repo) {
    @(
        "/* Generated by installer/build.ps1 - do not edit, do not commit. */",
        "#pragma once",
        "#define XBT_REPO L`"$Repo`""
    ) | Set-Content -Path $Config -Encoding ascii
} elseif (Test-Path $Config) {
    Remove-Item $Config -Force
}

function Find-Msvc {
    $vswhere = Join-Path ${env:ProgramFiles(x86)} "Microsoft Visual Studio\Installer\vswhere.exe"
    if (-not (Test-Path $vswhere)) { return $null }

    $install = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>$null
    if (-not $install) { return $null }

    $vcvars = Join-Path $install "VC\Auxiliary\Build\vcvars64.bat"
    if (Test-Path $vcvars) { return $vcvars }
    return $null
}

function Build-Msvc($vcvars) {
    Write-Host "  Toolchain: MSVC" -ForegroundColor Gray

    # cl and rc only exist inside a developer environment. When the caller has already set
    # one up (CI does, via msvc-dev-cmd), cl is on PATH and vcvars is skipped.
    $prelude = if ($vcvars) { "call `"$vcvars`" >nul" } else { "rem cl is already on PATH" }

    $script = @"
@echo off
$prelude
if errorlevel 1 exit /b 1
rc.exe /nologo /i "$Out" /fo "$Out\installer.res" "$Rc"
if errorlevel 1 exit /b 1
cl.exe /nologo /W3 /O2 /MT /EHsc /std:c++17 /I "$Out" /I "$Here" /Fe:"$Exe" /Fo:"$Out\\" "$Source" "$Out\installer.res" /link /SUBSYSTEM:WINDOWS /MANIFEST:EMBED /MANIFESTINPUT:"$Here\app.manifest"
if errorlevel 1 exit /b 1
"@

    $batch = Join-Path $Out "build.bat"
    Set-Content -Path $batch -Value $script -Encoding ascii

    & cmd.exe /c "`"$batch`""
    if ($LASTEXITCODE -ne 0) { throw "MSVC build failed" }
}

function Build-Mingw {
    Write-Host "  Toolchain: MinGW" -ForegroundColor Gray

    $gxx = (Get-Command g++ -ErrorAction SilentlyContinue).Source
    $windres = (Get-Command windres -ErrorAction SilentlyContinue).Source
    if (-not $gxx -or -not $windres) { throw "g++ and windres must both be on PATH" }

    $res = Join-Path $Out "installer_res.o"

    & $windres "-I$Here" "-I$Out" "-O" "coff" $Rc "-o" $res
    if ($LASTEXITCODE -ne 0) { throw "windres failed" }

    # GCC's mingw spec links default-manifest.o into every non-shared binary and there is no
    # flag to turn that off, so ld ends up with two non-default manifests and refuses to
    # merge them. The way out is to *be* default-manifest.o: build ours under that name and
    # put its directory first on the startfile search path with -B, so the spec finds this
    # one instead of the toolchain's.
    $manifestRc = Join-Path $Out "default-manifest.rc"
    $manifestObj = Join-Path $Out "default-manifest.o"
    Set-Content -Path $manifestRc -Encoding ascii -Value @(
        "#include <windows.h>",
        "1 RT_MANIFEST `"app.manifest`""
    )

    & $windres "-I$Here" "-O" "coff" $manifestRc "-o" $manifestObj
    if ($LASTEXITCODE -ne 0) { throw "windres failed on the manifest" }

    # UNICODE/_UNICODE are defined in the source, so they are deliberately not repeated here.
    $arguments = @(
        "-std=c++17", "-O2", "-municode", "-mwindows",
        "-I", $Out, "-I", $Here, "-B", $Out,
        "-static", "-static-libgcc", "-static-libstdc++",
        $Source, $res, "-o", $Exe,
        # Order matters for the GNU linker: libraries come after the objects that need them.
        "-lcomctl32", "-lshlwapi", "-lshell32", "-lole32", "-luuid",
        "-lwinhttp", "-luxtheme", "-lgdi32", "-luser32", "-ladvapi32"
    )

    & $gxx @arguments
    if ($LASTEXITCODE -ne 0) { throw "g++ failed" }
}

Write-Host ""
Write-Host "  Xbtcord installer" -ForegroundColor Magenta
if ($Repo) {
    Write-Host "  Release source: $Repo" -ForegroundColor DarkGray
} else {
    Write-Host "  No -Repo given: the exe will only install from an adjacent dist\" -ForegroundColor DarkYellow
}
Write-Host ""

$haveCl = [bool] (Get-Command cl.exe -ErrorAction SilentlyContinue)
$vcvars = if (-not $haveCl -and $Toolchain -ne "mingw") { Find-Msvc } else { $null }

if ($Toolchain -eq "msvc" -or (($Toolchain -eq "auto") -and ($haveCl -or $vcvars))) {
    if (-not $haveCl -and -not $vcvars) { throw "MSVC was requested but no Visual Studio with the C++ tools was found" }
    Build-Msvc $vcvars
} else {
    Build-Mingw
}

if (-not (Test-Path $Exe)) { throw "The build reported success but produced no exe" }

$size = [math]::Round((Get-Item $Exe).Length / 1KB)
Write-Host ""
Write-Host "  Built $Exe ($size KB)" -ForegroundColor Green
Write-Host ""
